import Head from 'next/head'
import Image from 'next/image'
import Footer from '../comps/footer'
import Navbar from '../comps/navbar'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>TechLover</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <div className="content">
        
        <h1 className={styles.title}>
          TechLover
        </h1>
        <p className={styles.text}>loremdnjvnd vbanuygyyyy vfjgf jtdsgrfyyugdhfdcc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremdgftcftfghftvft6ynjvnd vbancc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremduy65cgfjtgrfgvfgyjnjvnd vbancc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremdnjvnd vbancc dtyutyugygygyghgyghgchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremdnjvnd vbancc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremdnjvnd vbancc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremdnjvnd vbancc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <p className={styles.text}>loremdnjvnd vbancc dchd dcd cbd ddcdbcd chc dcygdc bc dhcd cdyc dycvedb dycvb cdyc cycvh cdcbcdcc</p>
        <Link href="/contact"><a className={styles.btn}>Contact Us</a></Link>

      
      </div>

      
    </div>
  )
}
